### ISSUE TITLE
Update build.sh to handle deeper paths

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards-starter#2]
The rewrite to the keyboard submission guide sillsdev/keyman-help.keyman.com#183 will direct keyboard contributors to structure their files along the lines of:
```
c:\projects\keyboards-starter\sample1\release\s\sample1
```

The keyboards-starter `build.sh` needs to be updated to handle this new pathing.

**Comment by mcdurdin** [comment]
I would like to do this by rewriting the build.sh to support either model. If it detects presence of `/release/` folder, then it assumes we are in the keyboards repo. If not, then assumes starter repo. That way we can have a single version of the build script rather than having them diverge too much.
